---
title: "Appendix S3"
output: 
  pdf_document:
    fig_caption: false
    
---
# Matthew T. Farr, David S. Green, Kay E. Holekamp, Gary J. Roloff, and Elise F. Zipkin

# Multispecies hierarchical modeling reveals variable responses of African carnivores to management alternatives

# Ecological Applications

# Model Results

**Table S1.** Summary (mean, standard deviation, 95% credible interval [CI]) of parameter estimates from hierarchical multi-species distance sampling model. $\mu_{\sigma}$: mean of $\gamma0_s$; $\tau^2_{\sigma}$: variance of $\gamma0_s$; $\mu_{\alpha0}$: mean of $\alpha0_s$; $\tau^2_{\alpha0}$: variance of $\alpha0_s$; $\mu_{\alpha1}$: mean of $\alpha1_s$; $\tau^2_{\alpha1}$: variance of $\alpha1_s$; $\mu_{\beta1}$: mean of $\beta1_s$; $\tau^2_{\beta1}$: variance of $\beta1_s$; $\gamma0_s$: species-specific intercepts of $\sigma_{js}$; $\alpha0_s$: species-specific intercepts of $\lambda_{tjs}$; $\alpha1_s$: species-specific effects of management regime on $\lambda_{tjs}$; $\beta0_s$: species-specific intercepts of $\mu_{tjs}$; $\beta1_s$: species-specific effects of management regime on $\mu_{tjs}$; $\gamma1$: effect of body size on $\sigma_{js}$; $\gamma2$: effect of management regime on $\sigma_{js}$; $Density_{s,MT}$: species-specific density in Mara Triangle; $Density_{s,TR}$: species-specific density in the Talek region; AL: African lion; BM: banded mongoose; BEF: bat-eared fox; BBJ: black-backed jackal; CAR: caracal; CHE: cheetah; LEO: leopard; SER: serval; SSJ: side-striped jackal; SM: slender mongoose; SH: spotted hyena.

Parameter | Mean | SD | 2.5% CI | 97.5% CI
--- | --- | --- | --- | --- 
$\mu_{\sigma}$ | 4.13 | 0.22 | 3.66 | 4.53
$\tau^2_{\sigma}$ | 0.6 | 0.25 | 0.27 | 1.2
$\mu_{\alpha0}$ | -1.33 | 0.59 | -2.55 | -0.2
$\tau^2_{\alpha0}$ | 1.71 | 0.52 | 0.97 | 2.97
$\mu_{\alpha1}$ | -0.24 | 0.45 | -1.21 | 0.58
$\tau^2_{\alpha1}$ | 0.95 | 0.42 | 0.35 | 1.98
$\mu_{\beta1}$ | -0.65 | 0.37 | -1.48 | -0.03
$\tau^2_{\beta1}$ | 0.65 | 0.36 | 0.24 | 1.59
$\gamma0_{AL}$ | 3.98 | 0.59 | 2.82 | 5.18
$\gamma0_{BM}$ | 4.28 | 0.17 | 3.95 | 4.61
$\gamma0_{BEF}$ | 3.88 | 0.17 | 3.55 | 4.21
$\gamma0_{BBJ}$ | 4.62 | 0.14 | 4.34 | 4.9
$\gamma0_{CAR}$ | 3.77 | 0.56 | 2.61 | 4.79
$\gamma0_{CHE}$ | 4.67 | 0.27 | 4.22 | 5.26
$\gamma0_{LEO}$ | 3.6 | 0.53 | 2.49 | 4.57
$\gamma0_{SER}$ | 4.03 | 0.25 | 3.56 | 4.56
$\gamma0_{SSJ}$ | 4.4 | 0.32 | 3.84 | 5.09
$\gamma0_{SM}$ | 3.56 | 0.38 | 2.8 | 4.25
$\gamma0_{SH}$ | 4.59 | 0.1 | 4.41 | 4.79
$\alpha0_{AL}$ | -0.59 | 0.26 | -1.14 | -0.13
$\alpha0_{BM}$ | 0.54 | 0.35 | -0.21 | 1.13
$\alpha0_{BEF}$ | -1.87 | 1.08 | -4.2 | 0.04
$\alpha0_{BBJ}$ | 0.03 | 0.35 | -0.74 | 0.63
$\alpha0_{CAR}$ | -3.05 | 1.12 | -5.57 | -1.04
$\alpha0_{CHE}$ | -2.73 | 0.62 | -4.09 | -1.67
$\alpha0_{LEO}$ | -2.71 | 0.99 | -4.81 | -0.89
$\alpha0_{SER}$ | -1.36 | 0.54 | -2.56 | -0.42
$\alpha0_{SSJ}$ | -2.91 | 0.79 | -4.64 | -1.57
$\alpha0_{SM}$ | -1.06 | 0.71 | -2.5 | 0.33
$\alpha0_{SH}$ | 0.99 | 0.21 | 0.55 | 1.38
$\alpha1_{AL}$ | -1.2 | 0.58 | -2.38 | -0.1
$\alpha1_{BM}$ | -0.19 | 0.53 | -1.24 | 0.89
$\alpha1_{BEF}$ | -0.48 | 0.97 | -2.57 | 1.33
$\alpha1_{BBJ}$ | 0.63 | 0.53 | -0.4 | 1.71
$\alpha1_{CAR}$ | -0.61 | 1.04 | -3.05 | 1.12
$\alpha1_{CHE}$ | 0.02 | 0.7 | -1.39 | 1.39
$\alpha1_{LEO}$ | -0.73 | 1.02 | -3.18 | 0.93
$\alpha1_{SER}$ | -0.68 | 0.79 | -2.45 | 0.68
$\alpha1_{SSJ}$ | 0.18 | 0.8 | -1.38 | 1.81
$\alpha1_{SM}$ | -0.27 | 0.72 | -1.81 | 1.07
$\alpha1_{SH}$ | 0.65 | 0.39 | -0.13 | 1.43
$\beta0_{AL}$ | 1.23 | 0.14 | 0.95 | 1.51
$\beta0_{BM}$ | 2.43 | 0.12 | 2.2 | 2.66
$\beta0_{BEF}$ | 0.92 | 0.17 | 0.58 | 1.27
$\beta0_{BBJ}$ | 0.26 | 0.15 | 0.02 | 0.59
$\beta0_{CHE}$ | 0.33 | 0.28 | 0.01 | 1.02
$\beta0_{SM}$ | 0.37 | 0.29 | 0.01 | 1.07
$\beta0_{SH}$ | 0.11 | 0.08 | 0 | 0.31
$\beta1_{AL}$ | -0.93 | 0.52 | -2.07 | -0.03
$\beta1_{BM}$ | -0.4 | 0.22 | -0.82 | 0.04
$\beta1_{BEF}$ | -0.99 | 0.63 | -2.45 | 0.03
$\beta1_{BBJ}$ | -0.7 | 0.28 | -1.27 | -0.18
$\beta1_{CHE}$ | -0.6 | 0.55 | -1.78 | 0.4
$\beta1_{SM}$ | -0.97 | 0.77 | -2.84 | 0.19
$\beta1_{SH}$ | 0.03 | 0.17 | -0.31 | 0.36
$\gamma1$ | 0.52 | 0.07 | 0.39 | 0.65
$\gamma2$ | 0.43 | 0.22 | -0.01 | 0.87
$Density_{AL,MT}$ | 2.23 | 0.5 | 1.41 | 3.36
$Density_{BM,MT}$ | 28.21 | 5.21 | 19.17 | 39.65
$Density_{BEF,MT}$ | 7.73 | 1.77 | 4.75 | 11.63
$Density_{BBJ,MT}$ | 1.86 | 0.42 | 1.18 | 2.81
$Density_{SH,MT}$ | 3.49 | 0.45 | 2.71 | 4.46
$Density_{AL,TR}$ | 0.35 | 0.24 | 0.07 | 0.95
$Density_{BM,TR}$ | 24.37 | 6.4 | 14.06 | 39.1
$Density_{BEF,TR}$ | 0.66 | 0.57 | 0.07 | 2.15
$Density_{BBJ,TR}$ | 2.4 | 0.69 | 1.29 | 3.95
$Density_{SH,TR}$ | 10.63 | 1.53 | 7.92 | 13.86